spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/wzweb
#    url: jdbc:mysql://sgpdatabase.ctc088yuet8v.us-east-1.rds.amazonaws.com/wzweb
    username: root
#    username: admin
#    password: wz199744
    password: 123456
  mail:
    host: smtp.qq.com
    username: 1546860437@qq.com
    password: siathtausyfzgfjj
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
#          starttls:
#            enable: false
          socketFactory:
            fallback: false
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
            required: false
        debug: true
